name: Build Windows

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Qt 6.11.2
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.2'
          host: windows
          target: desktop
          arch: win64_mingw
          modules: 'qtquickcontrols2'

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S . -B build `
            -G "MinGW Makefiles" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build application
        shell: pwsh
        run: |
          cmake --build build --config Release

      - name: Create deployment directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path package

      - name: Deploy Qt
        shell: pwsh
        run: |
          windeployqt `
            --release `
            --qmldir . `
            --dir package `
            build/appmtgDeckBuilder.exe

      - name: Copy application
        shell: pwsh
        run: |
          Copy-Item `
            build/appmtgDeckBuilder.exe `
            package/appmtgDeckBuilder.exe

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path package/* `
            -DestinationPath mtgDeckBuilder-Windows.zip

      - name: Upload Windows application
        uses: actions/upload-artifact@v4
        with:
          name: mtgDeckBuilder-Windows
          path: mtgDeckBuilder-Windows.zip
